language: python

install: pip install -U tox
script: tox -v

jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
      dist: xenial

    - stage: coverage
      python: 3.4
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls

    - stage: deploy
      python: 3.4
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: renatahodovan
        password:
          secure: yDpVN1T0xwNzxS0uNSVtRntEqxKIaWiF+C0Zy5l0qc6b/Fo5qzmV+Zcm9K5gUmv3wwQ/uR4RI30LBJHiZXzgFpWODKw82pVzuJ2ytLzU5NxPVGzmw5sx6oCjB0DnkrSHJQPwtGXS+g5yeGJ3udz0DBlS/pLl1U9vJ+1rhNV/9SM0LumdUpAJXjXieM3I3/ATMSFLlgjRZJtMcDEGiB8GS4GDwl8dTCVPxC/RgBiqIveOO8ON/JJQWKx8fgWUGZPqcy9YjTgnrswHtzHPRLnn0zu/bjeIsQml2spAGVnqbGqWLLXqsnlVHE/LI7yxpJzdswEqKYCk+QgLiPtM9rXWnQv0dk4ZNwXuxk0pPbvixNWXnUuCX+BYhAaGZfmsdWSnE0KFK+Hag+X1fWoBLG6pJ2vYeDTdoUt3JWQ5n6OYE3VakCT8CyXvHEgPgaI6HZeldCSH95WYrr2PIfmcnt5Q8v97xggGi9xy9oHPrUTpo2QRXQr3tGcdYooeX5MvyXvBIYW/AQjyNwhDK6TIO0BP6ggei5JBgaFjOmC6HOPS8W4Wdw+8F69WbTdIAg1S+A2ZjfsYWfeFDvGypnCjzkIOIHOTI2G1R4QRTqZj9bYnnm1pHesiiHEoKc/oVZI6FiEOAhyyNV57CiixqIw0ALt4EmVFe8QbuI+/gsFauRxajSg=
        on:
          repo: renatahodovan/picireny
          tags: true
