language: python

install: pip install -U tox
script: tox -v

jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
      dist: xenial

    - stage: deploy
      python: 3.4
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: renatahodovan
        password:
            secure: yA7IQD3u3KwgDztqYOPt1OW81GruBFg4X6oQpqtUPC/LZf1Wi+YWov2u/nd4wLS0Q2KlImfB/hl77qT2vU8ibi8sYhLUJqia6EItF39GzsBpGsr33Htya3zbVRhMbmjQZMhIy8UEB3ItAy/pw3otf3hAJGNjf6uN7wot3QmHHAVHcDGTJsdo+uJPc1Kf5qaU3zjaOxl9L8CtUH4Q2hR3y5qMcPb66l840pU7vkdQGmkVsq3UM6fygAJKZ55pEq1Bd0csYnUM1aE1X28rTsgLKc9mjSok+VXeSlcqVygY8s0hH+ZmgO/v0/mxmg1QBZBhyWfncd9xGUYxD4j/1HC+akpj/oVLvGk4nzb9W/a8XeHUm4E5sT60ry0UMbyCVnvDDB3cO+Wan4G3lpQx0adjzdaUXU4U5qSEzdTsM5FNANfCpiWuZW8+lB9EvnFCLcSLXi9h8eLdLCIswn3THSojo5viqxEJkLTXLwH5w/KApxPn2ogBf2TKGUYcXv/bmJVYwuSz7Svhep87NjFK7NTcdPEaS6OkQs4BiCzVTjfLLxwMK27mkRVrlFkySggCe4xWPxIq3ZwQUYxJQTdjI2iuQdCS1rzrQCByRc5GXtjsT+Rf2jC6s4gYvGFTnm4gpRt3BzCYfR7fzbBIyMFP4tiWq8W8gdvsv383C5gPDUy5S0w=
        on:
          repo: renatahodovan/antlerinator
          tags: true
